<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="1" failed="0" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-08-21T12:12:36 IST" name="Default suite" finished-at="2024-08-21T12:14:05 IST" duration-ms="89443">
    <groups>
    </groups>
    <test started-at="2024-08-21T12:12:36 IST" name="Default test" finished-at="2024-08-21T12:14:05 IST" duration-ms="89443">
      <class name="tests.CreateOrgWithTypeAndIndustryTest">
        <test-method is-config="true" signature="classConfig()[pri:0, instance:tests.CreateOrgWithTypeAndIndustryTest@443118b0]" started-at="2024-08-21T12:12:36 IST" name="classConfig" finished-at="2024-08-21T12:12:52 IST" duration-ms="16519" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- classConfig -->
        <test-method is-config="true" signature="methodConfig()[pri:0, instance:tests.CreateOrgWithTypeAndIndustryTest@443118b0]" started-at="2024-08-21T12:12:52 IST" name="methodConfig" finished-at="2024-08-21T12:13:24 IST" duration-ms="31504" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodConfig -->
        <test-method signature="createOrgTest()[pri:0, instance:tests.CreateOrgWithTypeAndIndustryTest@443118b0]" started-at="2024-08-21T12:13:24 IST" name="createOrgTest" finished-at="2024-08-21T12:13:56 IST" duration-ms="31713" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createOrgTest -->
        <test-method is-config="true" signature="methodTeardown()[pri:0, instance:tests.CreateOrgWithTypeAndIndustryTest@443118b0]" started-at="2024-08-21T12:13:56 IST" name="methodTeardown" finished-at="2024-08-21T12:14:05 IST" duration-ms="9342" status="FAIL">
          <exception class="org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException">
            <message>
              <![CDATA[Fail to save: an error occurs while saving the package : Cannot invoke "java.io.OutputStream.write(byte[], int, int)" because "this.os" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : Cannot invoke "java.io.OutputStream.write(byte[], int, int)" because "this.os" is null
at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:643)
at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1532)
at org.apache.poi.ooxml.POIXMLDocument.write(POIXMLDocument.java:227)
at genericUtilities.ExcelUtility.saveExcel(ExcelUtility.java:74)
at genericUtilities.BaseClass.methodTeardown(BaseClass.java:62)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:833)
at org.testng.internal.invokers.TestInvoker.runAfterConfigurations(TestInvoker.java:802)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:778)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.NullPointerException: Cannot invoke "java.io.OutputStream.write(byte[], int, int)" because "this.os" is null
at org.apache.commons.compress.archivers.zip.StreamCompressor$OutputStreamCompressor.writeOut(StreamCompressor.java:67)
at org.apache.commons.compress.archivers.zip.StreamCompressor.writeCounted(StreamCompressor.java:311)
at org.apache.commons.compress.archivers.zip.StreamCompressor.writeCounted(StreamCompressor.java:307)
at org.apache.commons.compress.archivers.zip.ZipArchiveOutputStream.writeCounted(ZipArchiveOutputStream.java:1820)
at org.apache.commons.compress.archivers.zip.ZipArchiveOutputStream.writeLocalFileHeader(ZipArchiveOutputStream.java:1872)
at org.apache.commons.compress.archivers.zip.ZipArchiveOutputStream.putArchiveEntry(ZipArchiveOutputStream.java:1361)
at org.apache.commons.compress.archivers.zip.ZipArchiveOutputStream.putArchiveEntry(ZipArchiveOutputStream.java:1301)
at org.apache.poi.openxml4j.opc.internal.ZipContentTypeManager.saveImpl(ZipContentTypeManager.java:65)
at org.apache.poi.openxml4j.opc.internal.ContentTypeManager.save(ContentTypeManager.java:450)
at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:608)
... 37 more
]]>
            </full-stacktrace>
          </exception> <!-- org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodTeardown -->
        <test-method is-config="true" signature="classTeardown()[pri:0, instance:tests.CreateOrgWithTypeAndIndustryTest@443118b0]" started-at="2024-08-21T12:14:05 IST" name="classTeardown" finished-at="2024-08-21T12:14:05 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- classTeardown -->
      </class> <!-- tests.CreateOrgWithTypeAndIndustryTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
